### ISSUE TITLE
Speaker icon overlaps website icon

### ISSUE THREAD

**Issue by ghost** [Guerra24/Firefox-UWP-Style#45]
![image](https://user-images.githubusercontent.com/85873175/150909882-4f3e499b-e19d-494f-9310-d6975eb34656.png)
The picture describes it all.

**Comment by Guerra24** [comment]
This is intended since the icon was moved to the left side and I wanted to keep the speaker visible all the time and placing it right above the favicon was the best option.

**Comment by ghost** [comment]
But it looks kind of odd. Could you move it to the side of the favicon?

**Comment by Guerra24** [comment]
Sorry but no. You can add this code into `customChrome.css` if you want it like that.
```css
.tab-icon-stack[soundplaying="true"] {
	margin-right: 20px !important;
}
.tab-icon-overlay {
	left: 21px !important;
	top: 0px !important;
}
```
