### ISSUE TITLE
Remove "white" top border

### ISSUE THREAD

**Issue by zcresh** [Guerra24/Firefox-UWP-Style#62]
how do I change/remove the top border that can be changed with `ui.-moz-accent-color`.
P.S.: only the top line of the browser not the one above the tabs.

[Example](https://i.imgur.com/vjudf47.png)

**Comment by Guerra24** [comment]
Add this into `customChrome.css`
```css
#main-window[sizemode="normal"][tabsintitlebar] #navigator-toolbox {
	border-top: 1px solid red !important;
}
```
