### ISSUE TITLE
remove compact mode

### ISSUE THREAD

**Issue by e-splat** [Guerra24/Firefox-UWP-Style#65]
i hate compact mode, is too small, make compact mode optional please.

**Comment by Guerra24** [comment]
Hi. No, I'm not gonna change the default size but there is an alternative: set the size to your preferred one. Add this into `customChrome.css`.
```css
:root {
	--tab-min-height: 50px !important;
	--uwp-urlbar-height: 50px !important;
}
```
