### ISSUE TITLE
reduce bookmark padding

### ISSUE THREAD

**Issue by geextahslex** [Guerra24/Firefox-UWP-Style#81]
Hi, I like this theme but I would like to make 2 changes. How can I achieve this?
1. Reduce the padding between bookmarks
2. add a delay to the flyouts folders. So it takes some time to show and hide it.

Thank you
![firefox changes 2](https://github.com/Guerra24/Firefox-UWP-Style/assets/139760266/5d36df11-c13a-486d-b78c-1d553ebe4a7d)

**Comment by Guerra24** [comment]
Hello!

1. You can use the following selector to change that.
```css
menupopup menuitem.bookmark-item {
    margin: 2px 4px !important;
}
```
2. I don't know, AFAIK you can't change it through CSS.
